# Generated by Django 2.2.13 on 2020-12-31 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('original_link', models.CharField(blank=True, max_length=255, unique=True)),
                ('generated_link', models.CharField(blank=True, max_length=20)),
                ('visits', models.BigIntegerField(default=0)),
                ('date_created', models.DateField(auto_now=True)),
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.SmallIntegerField(default=0)),
                ('email_confirm', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
